---
framework: jest
licenseTier: medium
postMerge: 
  pattern: 
    - "./test/*/*.test.js"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/*/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.0
