---
framework: jest
tier: large
postMerge: 
  pattern: 
    - "./test/*/create.test.js"
preMerge:
  pattern:
    - "./test/*/create.test.js"
preRun:
     command:
        - npm install
        - npm run build
postRun:
     command:
        - node --version
version: 2.1
